[package]
name = "wasm"
version = "0.1.0"
authors = ["Virgiel"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
wee_alloc = "0.4.5"
tml = { path = "../tml" }
js-sys = "0.3"