[package]
name = "repl"
version = "0.1.0"
authors = ["Virgiel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tml = { path = "../tml" }
rustyline = "8.0.0"
rustyline-derive = "0.4.0"
